require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "vendor/bundle/**/*"
    - "vendor/bin/**/*"
    - ",/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - "app/views/**/*"
    - "config/**/*.rb"
    - "spec/factories/**/*.rb"
    - "Guardfile"

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: true

Style/MixinGrouping:
  Enabled: true
  Exclude:
    - 'rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/*_spec.rb'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/IfUnlessModifier:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - 'spec/requests/**/*_spec.rb'
    - 'spec/jobs/**/*_spec.rb'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/requests/**/*_spec.rb'
    - 'spec/jobs/**/*_spec.rb'