default: &default
  adapter: postgresql
  encoding: unicode
  strict: true
  pool: <%= ENV["PUMA_MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: folicolle_development

test:
  <<: *default
  database: folicolle_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
