name: integration

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    types:
      - reopened

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: execute rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          github_token: ${{ secrets.GH_TOKEN }}
          rubocop_flags: --fail-level R --display-only-fail-level-offenses
          level: error
          reporter: github-check
          fail_on_error: true