name: Move new issues into folicolle development
on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: folicolle
          column_name: Todo
