name: Move new issues into folicolle development
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: https://github.com/users/wakidas/projects/1
          column: Todo
          repo-token: ${{ secrets.GH_TOKEN }}
