name: RSpec
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    types:
      - reopened
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: folicolle_test
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    container:
      image: cimg/ruby:3.1.0
      env:
        TZ: Asia/Tokyo
        RAILS_ENV: test
        PGHOST: postgres
        PGUSER: postgres
    steps:
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Setup database/
        run: bundle exec rails db:setup
      - name: Run rspec
        run: bundle exec rspec
