name: RSpec
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    types:
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: folicolle_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 3.0.1
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle --without production
          yarn install
      - name: Set env
        run: |
          echo '::set-env name=RAILS_ENV::test'
          echo '::set-env name=DATABASE_URL::postgres://postgres:postgres@localhost:5432/my_database'
      - name: setup DB
        run: |
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec